image:
  - Visual Studio 2017

configuration:
  - Release
  - Debug

init:
- IF "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( SET generator="Visual Studio 15 2017 Win64" )

before_build:
- cmd: |-
    MKDIR build
    CD build
    cmake --version
    cmake .. -G %generator% "-DCMAKE_BUILD_TYPE=%configuration%" -DOSMPBF_BUILD_TESTS=ON
    cmake --build . --config %configuration% -- /nologo

build_script:
  - cmake --build . --config %configuration%
  - ctest --build-config %configuration%
